version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keepwatch-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/keepwatch?schema=public"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: keepwatch-postgres
    ports:
      - "7864:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keepwatch
    volumes:
      - keepwatch-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  keepwatch-postgres-data:
