version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: keepwatch-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Lyot
      POSTGRES_PASSWORD: S0S@L0N10n
      POSTGRES_DB: keepwatch
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Lyot"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
